#!/usr/bin/env python3
"""Export a recovered Hoodie Bass scalar patch as a playable eseq instrument."""

import argparse
import json
from pathlib import Path


BANKS = (
    ("steady", "h", 1, "1.0"),
    ("slow", "bh", 2, "slow_env"),
    ("medium", "mh", 2, "medium_env"),
    ("fast", "fh", 2, "fast_env"),
)


def scalar(value):
    return format(float(value), ".9g")


def bank_source(name, prefix, first_harmonic, envelope, coefficients):
    terms = []
    for harmonic in range(first_harmonic, 33):
        for suffix, function in (("s", "hs"), ("c", "hc")):
            value = float(coefficients.get(f"{prefix}{harmonic}{suffix}", 0.0))
            if abs(value) <= 1e-10:
                continue
            terms.append(f"    ({function} {scalar(value)} {harmonic} {envelope})")
    if not terms:
        return f"(def {name} 0.0)"
    return f"(def {name}\n  (+\n" + "\n".join(terms) + "))"


def render(params, source_label, improvement, distance):
    coefficients = params["harmonicCorrections"]
    banks = "\n\n".join(
        bank_source(name, prefix, first, envelope, coefficients)
        for name, prefix, first, envelope in BANKS)
    return f"""; SynthID Hoodie Bass — Korg Monologue multisample identification.
;
; Generated by export_eseq_hoodie_bass.py from {source_label}.
; The 32 integer-locked steady partials and three attack-decay banks are
; ordinary recovered scalar coefficients, not target samples or a wavetable.
; Independent MR-STFT: {improvement:.2%} improvement, distance {distance:.6f}.
; MIDI pitch replaces the identified {params['f0']:.6f} Hz fundamental.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))

; Playable adaptation: the captured fixed note-off becomes a gate-aware ADSR.
(param amp_attack @default {params['attackTime'] * 1000:.6f} @min 1 @max 1000 @unit ms)
(param amp_decay @default {params['decayTime'] * 1000:.6f} @min 1 @max 2500 @unit ms)
(param amp_sustain @default {params['sustain']:.9g} @min 0 @max 1)
(param amp_release @default {params['releaseTime'] * 1000:.6f} @min 1 @max 4000 @unit ms)
(param brightness_decay @default {params['brightnessDecay']:.9g} @min 0.1 @max 30 @unit 1/s)
(param drive @default {params['drive']:.9g} @min 0.1 @max 4)
(param gain @default {params['outGain']:.9g} @min 0 @max 1)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))

(make-history time_h)
(def previous_time (read-history time_h))
(def triggered (gt trigger 0.5))
(def t (gswitch triggered 0.0 previous_time))
(write-history time_h (+ t (/ 1.0 samplerate)))
(def phase (* pitch t twopi))
(def slow_env (exp (* -1.0 brightness_decay t)))
(def medium_env (exp (* -2.0 brightness_decay t)))
(def fast_env (exp (* -4.0 brightness_decay t)))

(defmacro hs (coefficient harmonic envelope)
  (* coefficient (sin (* phase harmonic)) envelope))
(defmacro hc (coefficient harmonic envelope)
  (* coefficient (cos (* phase harmonic)) envelope))

{banks}

(def oscillator (+ steady slow medium fast))
(def driven (* oscillator amp_env drive))
(def softsign (/ driven (+ 1.0 (abs driven))))
(out (* softsign gain velocity) 1 @name audio)
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--params", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--source-label", default="recovered_params.json")
    parser.add_argument("--improvement", required=True, type=float)
    parser.add_argument("--distance", required=True, type=float)
    args = parser.parse_args()
    params = json.loads(args.params.read_text())
    if "params" in params:
        params = params["params"]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        render(params, args.source_label, args.improvement, args.distance),
        encoding="utf-8")


if __name__ == "__main__":
    main()
